name: itonatalaga
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  just_audio: ^0.9.39
  just_audio_windows: ^0.2.0

  flame: ^1.33.0
  shared_preferences: ^2.3.1
  vector_math: ^2.1.4
  flame_audio: ^2.11.11



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/house.png
    - assets/activity3.png
    - assets/activity4.png
    - assets/opening.mp3
    - assets/activity1.gif
    - assets/music/
    - assets/album-cover/
    - assets/images/activity2/maps/level1/floor.png
    - assets/images/activity2/maps/level2/floor.png
    - assets/images/activity2/maps/level3/floor.png
    - assets/images/activity2/maps/level1/assets/
    - assets/images/activity2/maps/level2/assets/
    - assets/images/activity2/maps/level3/assets/
    - assets/images/activity2/players/
    - assets/images/activity2/monsters/level1/
    - assets/images/activity2/monsters/level2/
    - assets/images/activity2/monsters/level3/
    - assets/images/activity2/weapons/
    - assets/audio/


  fonts:
      - family: PlayfairDisplay
        fonts:
          - asset: assets/PlayfairDisplay-Black.ttf
      - family: Poppins
        fonts:
          - asset: assets/Poppins-Light.ttf

