name: itonatalaga
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  just_audio: ^0.9.39


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/house.png
    - assets/activity3.png
    - assets/activity4.png
    - assets/opening.mp3
    - assets/activity1.gif
    - assets/music/
    - assets/album-cover/
    - assets/activity2/
  fonts:
      - family: PlayfairDisplay
        fonts:
          - asset: assets/PlayfairDisplay-Black.ttf
      - family: Poppins
        fonts:
          - asset: assets/Poppins-Light.ttf

